### ISSUE TITLE
2.1.3 version is not available in maven central/jcenter

### ISSUE THREAD

**Issue by muzuro** [goshippo/shippo-java-client#44]
https://search.maven.org/ still returns **2.1.2** as latest version.
https://bintray.com/bintray/jcenter/com.goshippo%3Ashippo-java-client also have only **2.1.2**.

**Comment by assislucas** [comment]
Hi @muzuro this might be a problem with our version naming, if you look here https://search.maven.org/artifact/com.goshippo/shippo-java-client you can see that the latest version is actually `v2.1.6`.

So can you try to specify that version directly when using the dependency and see if that works? I believe it should work since v2.1.6 shows as available on maven.

Thanks!

**Comment by muzuro** [comment]
Yes, there is `v2.1.6`. I was confused because "2.1.3" is specified at main readme: https://github.com/goshippo/shippo-java-client/blob/master/README.md

**Comment by ryanmckaytx** [comment]
3.2.0 is verified in https://search.maven.org/
Readme has been updated to point to 3.2.0
